# Generated by Django 4.0 on 2022-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_description_poll_finish_poll_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='finish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
