# Generated by Django 4.0 on 2022-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_finish_alter_poll_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
