# Generated by Django 4.0 on 2022-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_finish_alter_poll_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='poll_type',
            field=models.CharField(choices=[('text', 'Text'), ('select_one', 'Select One'), ('select_multiple', 'Select Multiple')], default='text', max_length=50, verbose_name='Types of polls'),
        ),
    ]
