# Generated by Django 4.0 on 2022-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two_count',
        ),
        migrations.AlterField(
            model_name='poll',
            name='finish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
