# Generated by Django 4.0 on 2022-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_poll_option_one_remove_poll_option_one_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('select_one', 'Select One'), ('select_multiple', 'Select Multiple')], default='text', max_length=50, verbose_name='Types of polls'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
