# Generated by Django 4.0 on 2022-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_poll_type_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
